<?php
use function PhpWeb\route_to;
use function App\base64_photo;
?>
<div class="container text-center">
    <div class="row justify-content-end mb-3">
        <div class="col-auto">
            <a href="<?= route_to('admin_list_guest') ?>" class="btn btn-success btn-block p-3"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" class="mr-3" fill="currentColor" stroke="none" viewBox="0 0 32 32" focusable="false">
                    <path d="M8.6620483,17.699996L32,17.699996 32,21.116015 8.6620483,21.116015z M2.6040039,16.805007C4.0390015,16.805007 5.2059937,17.97502 5.2059937,19.410996 5.2059937,20.851001 4.0390015,22.006 2.6040039,22.006 1.1640015,22.006 0,20.851001 0,19.410996 0,17.97502 1.1640015,16.805007 2.6040039,16.805007z M8.6620483,8.984993L32,8.984993 32,12.401011 8.6620483,12.401011z M2.6040039,8.0849981C4.0390015,8.0849981 5.2059937,9.2500076 5.2059937,10.690011 5.2059937,12.130015 4.0390015,13.290997 2.6040039,13.290997 1.1640015,13.290997 0,12.130015 0,10.690011 0,9.2500076 1.1640015,8.0849981 2.6040039,8.0849981z M8.6620483,0.82498215L32,0.82498215 32,4.2410006 8.6620483,4.2410006z M2.6040039,0C4.0390015,1.6889317E-08 5.2059937,1.1600046 5.2059937,2.6049824 5.2059937,4.0409884 4.0390015,5.2059979 2.6040039,5.2059979 1.1640015,5.2059979 0,4.0409884 0,2.6049824 0,1.1600046 1.1640015,1.6889317E-08 2.6040039,0z" />
                </svg>Ke Daftar Tamu</a>
        </div>
    </div>
    <h3 class="py-3"><strong>Informasi Tamu BPS</strong></h3>
    <div class="row">
        <div class="col-auto mx-auto">
            <table class="table border">
                <thead>
                    <tr>
                        <th>Foto</th>
                        <th colspan="3">Data</th>
                    </tr>
                </thead>
                <tbody class=" text-left">
                    <tr>
                        <td rowspan="6"><img width="360" class="img-fluid" src="<?= base64_photo($guest['foto']) ?>"></td>
                        <td>Nama</td>
                        <td>:</td>
                        <td><?= $guest['nama'] ?></td>
                    </tr>
                    <tr>
                        <td>Asal</td>
                        <td>:</td>
                        <td><?= $guest['asal'] ?></td>
                    </tr>
                    <tr>
                        <td>Keperluan</td>
                        <td>:</td>
                        <td><?= $guest['keperluan'] ?></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>:</td>
                        <td><?= $guest['email']??'-' ?></td>
                    </tr>
                    <tr>
                        <td>HP</td>
                        <td>:</td>
                        <td><?= $guest['hp'] ?></td>
                    </tr>
                    <tr>
                        <td>Tanggal Kunjungan</td>
                        <td>:</td>
                        <td><?= date('Y-m-d H:i:s', $guest['tanggal'])?></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Foto</th>
                        <th colspan="3">Data</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>