<?php

use Core\Config\Config;
?>
<!doctype html>
<html lang="en">

<head>
    <title><?= app()->config('application.name') . ' : Kesalahan' ?></title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- icons -->
    <link rel="icon" href="<?= asset('images/icons/bps-32x32.png') ?>" sizes="32x32" type="image/png">
    <link rel="icon" href="<?= asset('images/icons/bps-16x16.png') ?>" sizes="16x16" type="image/png">
    <link rel="shortcut icon" href="<?= asset('images/icons/bps.ico') ?>">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?= asset('css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?= asset('css/sweetalert2.min.css') ?>">

    <!-- custom style -->
    <link rel="stylesheet" href="<?= asset('css/main.css') ?>">
</head>

<body>

    <div class="container">
        <header>
            <div class="container bg-primary">
                <div class="row justify-content-center py-1">
                    <div class="col-auto">
                        <a href="<?= route_to('home') ?>" class="navbar-brand d-flex align-items-center btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" stroke="none" class="mr-3" focusable="false">
                                <path d="M11.299988,0L16.599976,0 7.0999756,8.8999959 32,8.8999959 32,12.399997 7.0999756,12.399997 16.5,21.299993 16.400024,21.399999 11.299988,21.399999 2.5999756,13.100009 0,10.699985z" />
                            </svg>
                            <strong>Ke Halaman Utama</strong>
                        </a>
                    </div>
                </div>
            </div>
        </header>

        <main role="main" class="py-5">

            <?= $content ?>

        </main>

        <footer class="footer text-center border-top border-primary py-2">
            <div class="container">
                <span class="text-dark"><?= app()->config('application.name') ?> versi <?= app()->config('application.version') ?> &copy; 2021 - <?= app()->config('application.vendor') ?></span>
            </div>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="<?= asset('js/jquery.min.js') ?>"></script>
    <script src="<?= asset('js/bootstrap.bundle.min.js') ?>"></script>
    <script src="<?= asset('js/sweetalert2.min.js') ?>"></script>

    <script>
        $(document).ready(function() {
            <?php if (app()->session()->hasFlash()) {
                foreach (app()->session()->flash() as $flash) {
                    echo $flash;
                }
            } ?>
        });
    </script>

</body>

</html>